name: Docker Build and Push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"

          docker build \
            -t "$DOCKER_USERNAME/day45-docker-cicd:latest" \
            -t "$DOCKER_USERNAME/day45-docker-cicd:sha-$SHORT_SHA" \
            .

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"

          docker push "$DOCKER_USERNAME/day45-docker-cicd:latest"
          docker push "$DOCKER_USERNAME/day45-docker-cicd:sha-$SHORT_SHA"
