name: Job Outputs

on:
  workflow_dispatch:

jobs:

  generate-date:
    runs-on: ubuntu-latest

    outputs:
      today: ${{ steps.date.outputs.today }}

    steps:
      - name: Get today's date
        id: date
        run: |
          echo "today=$(date '+%Y-%m-%d')" >> "$GITHUB_OUTPUT"

  display-date:
    needs: generate-date
    runs-on: ubuntu-latest

    steps:
      - name: Display date
        run: |
          echo "Today's date is: ${{ needs.generate-date.outputs.today }}"
