name: reusable build workflow

on:
  workflow_call:
    inputs:
      app_name:
        description: "App Name"
        required: true
        type: string
      environment:
        description: "Deploy Environment"
        required: true
        default: "staging"
        type: string
    secrets:
      docker_token:
        required: true
    outputs:   # Map the workflow outputs to job outputs
      build_version:
        value: ${{ jobs.build.outputs.build_version }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs: # Map the job outputs to step outputs
      build_version: ${{ steps.set-version.outputs.build_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print build info
        run: |
          echo "Building ${{ inputs.app_name }} for ${{ inputs.environment }}"

      - name: verify docker token status
        run: |
          if [ -n "${{ secrets.docker_token }}" ]; then
            echo "Docker token is set: true"
          else
            echo "Docker token is set: false"
          fi

      - name: Generate a version
        id: set-version
        run: |
         BUILD_VERSION="v1.0-${GITHUB_SHA::7}"
         echo "build_version=$BUILD_VERSION" >> $GITHUB_OUTPUT
         echo "Generated build version: $BUILD_VERSION"
