name: secrets

on:
 workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: check if secret is set
        run: |
          if [  -n "${{ secrets.MY_SECRET_MESSAGE }}"  ]; then
          echo "Secret is not set"
          else
          echo "Secret is set"
          fi

      - name: print secret
        run: echo "The secret is:" ${{ secrets.MY_SECRET_MESSAGE }}
