name: secrets-demo

on:
 workflow_dispatch: 

jobs:
  secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Docker secrets
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo "Docker username is $DOCKER_USERNAME"
          echo "Logging into Docker"
