name: Secret Environment Variable

on:
  workflow_dispatch:

jobs:
  secret-env:
    runs-on: ubuntu-latest

    steps:
      - name: Use secret
        env:
          MY_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}

        run: |
          if [ -n "$MY_MESSAGE" ]; then
            echo "Secret environment variable is available."
          else
            echo "Secret environment variable is not available."
            exit 1
          fi
