name: Secrets Demo

on:
  workflow_dispatch:

jobs:
  secret-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check secret
        env:
          SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}

        run: |
          if [ -n "$SECRET_MESSAGE" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi
